### ISSUE TITLE
Homework 95 Feedback # 1

### ISSUE THREAD

**Issue by jmai28** [Yeonhova/Purple-Boomerang-Profreshers#2]
Your approach to the problem is to solve through junctions. But, I believe that Mr. Holmes has stated that this is a valid approach, just not the best approach for this project.

On another note, your base case does not encapsulate all situations. What happens if there is no path? 
How does the base case return false other then when it is starting the recursive abstraction on a wall?

**Comment by YuenhighLee** [comment]
Continuing on what Justin mentioned above, your English/Pseudocode still uses the idea of junctions.

Also, for the recursive abstraction I think that you should specify one direction or have the user make the move to specify the direction since you don't  need the recursive abstraction to check in all possible directions when you only want to know if there is a possible path in the direction that you are headed. 

Moreover, I think that you should add some sort of  condition in your English/Pseudocode that will let you know that you have already stepped  over the current area to prevent that never ending walk on the "path stones" like Holmes mentioned in class.

**Comment by stevenTan01** [comment]
Your algorithm should probably state how other parts of your code will be structured, instead of restating what you would do when you encounter a base case or invoke the recursive abstraction. 

Also, it may be good to elaborate on what "a next step in a cardinal direction" is in your recursive abstraction. Otherwise everything else looks fine.

**Comment by Yeonhova** [comment]
Thanks! We appreciate it and will make sure to check these issues out!

**Comment by Yeonhova** [comment]
Thanks, we just changed the readme so that we place a wall on stepping stones we have passed. We also made sure the structure of our pseudocode more pseudocode-like. However, we did not want to check all the legal directions to step towards before moving. We feel that this defeats most of the purpose of the base case.
